# Uncomment the next line to define a global platform for your project
 platform :ios, '8.4'

target 'STScrolPlay' do
  use_frameworks!
pod 'SVProgressHUD', '~> 2.1.2'
pod 'Alamofire'
pod 'SDWebImage', '~> 3.8.0'
end
